<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseArtifactsOutput>true</UseArtifactsOutput>
    </PropertyGroup>

    <PropertyGroup>
        <CmdletVersion>8.0.0</CmdletVersion>
    </PropertyGroup>

</Project>