<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseArtifactsOutput>true</UseArtifactsOutput>
    </PropertyGroup>

    <PropertyGroup>
        <CmdletVersion>8.0.0</CmdletVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(ARTIFACTS_PATH_DOTNET)' != '' ">
        <MSBuildThisFileDirectoryName>$([System.IO.Path]::GetFileName($(MSBuildThisFileDirectory.TrimEnd($([System.IO.Path]::DirectorySeparatorChar)))))</MSBuildThisFileDirectoryName>
        <SolutionName Condition="'$(SolutionName)' == ''">$(MSBuildThisFileDirectoryName)</SolutionName>
        <ArtifactsPath>$(ARTIFACTS_PATH_DOTNET)\$(SolutionName)</ArtifactsPath>
    </PropertyGroup>

</Project>